# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c965e8e0f8ae49244e859ab6f0f37d8b72224059f3fb92bc1b1721ee3e9d62dc0194a57e250ab1d6294aa5eca47008d7cade03a76115e3ae123d8cac286734d

test:
  secret_key_base: 8a8a32e0030db8d1a2166161d9c5728af5948875f9dbe05660c24e19ce75c7608aae2d7f3ed44eed120144881b2e491f6b87e461bb6c470a1f17ddc67f2ac4bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
